[[dependencies]]
type = "build"
name = "wrk"
check_command = ["wrk", "--help"]
check_ret_code = 1
build_cmds = [
  "git clone https://github.com/wg/wrk .",
  "git submodule update --init --recursive || true",
  "make"
]
artifact_name = "wrk"
dest_name = "wrk"

[[dependencies]]
type = "build"
name = "wrk2"
check_command = ["wrk2", "--help"]
check_ret_code = 1
check_output_function = """
valid = "--rate" in stdout
"""
build_cmds = [
  "git clone https://github.com/giltene/wrk2 .",
  "git submodule update --init --recursive || true",
  "make"
]
artifact_name = "wrk"
dest_name = "wrk2"
